name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  lint:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up dev environment
        uses: ./.github/actions/setup-python-dev
        with:
          python-version: "3.11"

      - name: Install Linux system dependencies
        uses: ./.github/actions/install-linux-system-deps

      - name: Format project source
        run: ruff format --check .

      - name: Analyze project source
        run: ruff check .

  test:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up dev environment
        uses: ./.github/actions/setup-python-dev
        with:
          python-version: "3.11"

      - name: Install Linux system dependencies
        uses: ./.github/actions/install-linux-system-deps

      - name: Run tests and collect coverage
        run: |
          if [ -d tests ]; then
            pytest --cov-report=json
          else
            echo "No tests directory found, skipping pytest."
          fi

      - name: Upload coverage data
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: coverage.json
          retention-days: 1
          if-no-files-found: ignore
